### ISSUE TITLE
trouble with setting region with openstack4J and OVH

### ISSUE THREAD

**Issue by lisi1986** [openstack4j/openstack4j#101]
Hi, i'm having trouble setting the region for object storage with openstack4J and OVH cloud hosting. How should I setup the endpoint I need to use for object storage for a specific region? Regards!

**Comment by olivergondza** [comment]
Please direct questions to user group: https://groups.google.com/forum/#!forum/openstack4j.

**Comment by lisi1986** [comment]
Oliver, I tried to, but i cannot access the group but it does not allow me.
Maybe its because of my country. Could you please help me with my problem?
