### ISSUE TITLE
MigrationStatus lost

### ISSUE THREAD

**Issue by hoteam** [openstack4j/openstack4j#102]
MigrationStatus enums in class org.openstack4j.model.storage.block.Volume  is not complete, which losing :DELETING,ERROR,SUCCESS

**Comment by bboyHan** [comment]
Which REST API does this operation refer to ？

**Comment by hoteam** [comment]
‘/volumes/detail’  in class BlockVolumeServiceImpl which convert the response into Volume object . It will occur an exception when the response has DELETING,ERROR,SUCCESS MigrationStatus

**Comment by bboyHan** [comment]
Where can I find all the status of this field.  Can you provide a link to the details of this API ?

**Comment by simosda** [comment]
I am also having issues with missing values from migration status. Openstack doesn't clearly say what are All possible statuses, but please add at least the ones we know exist - None, deleting, error, success.
Source: [openstack migrate a volume](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=create-a-volume-type-detail,create-a-volume-detail,attach-volume-to-a-server-detail,detach-volume-from-server-detail,create-attachment-detail,migrate-a-volume-detail#migrate-a-volume)
Thanks

**Comment by cpolzer** [comment]
Hey the link to the corrent enum is here: https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/objects/fields.py#L204
