### ISSUE TITLE
How to create netQosPolicy

### ISSUE THREAD

**Issue by wly1456839489** [openstack4j/openstack4j#178]
![image](https://user-images.githubusercontent.com/29268326/157354888-51e495e5-0206-4184-9396-00b170bfc011.png)

**Comment by wly1456839489** [comment]
![M0M3T%BN$Y`WL)D M5M326H](https://user-images.githubusercontent.com/29268326/157355286-f7c5cb0d-1a08-4d2e-8f8d-d33c1d1670ee.jpg)

**Comment by zz22ss55** [comment]
![2022-11-07_090528](https://user-images.githubusercontent.com/52227313/200206729-da519bfc-c929-4371-93dc-4675e031370b.png)
![2022-11-07_090544](https://user-images.githubusercontent.com/52227313/200206738-3fbb3cdd-6fd0-4102-9a0b-ff40866e6418.png)
I cant creat yet，why？

**Comment by slankka** [comment]
same problem.

**Comment by slankka** [comment]
Solved by extends another NetQosPolicy class
```
@JsonRootName("policy")
public AnotherClass implements NetQosPolicy {

    @JsonProperty("is_default")
    public boolean isDefault() {
        return isDefault;
    }
}
```
