### ISSUE TITLE
Add a "heads up" in the README why this fork exists

### ISSUE THREAD

**Issue by sbrattla** [openstack4j/openstack4j#2]
Following up on the comment https://github.com/ContainX/openstack4j/issues/1266#issuecomment-555498584, how about adding a "heads up" message at the top of the README for this project which says why this fork exists. That is, maintenance was minimal / non-existent on the original project, and that this fork aims at actively maintain the code and keep up the good work done up until now?

**Comment by olivergondza** [comment]
Good idea. I am not convinced this belongs to README. So for now, I have added this to the repo description where I intend to keep it until we gain traction so this is no longer needed. Does that work for you?

**Comment by sbrattla** [comment]
Absolutely! Anywhere it can be seen. There are so many forks of this project, so having a notification where it says "this is the place to put your effort" somewhere it can be seen - regardless of where that specifically is - is probably good.

Thanks!
