### ISSUE TITLE
Unclear maintenance status of openstack4j

### ISSUE THREAD

**Issue by amuessig** [openstack4j/openstack4j#204]
Hi there,
I am unsure about the maintenance state of OpenStack4j. There was no release for ~2 years, now a release was created on the mvn repository for which I couldn't find the release here at github, only a tag for this release. Additionally there is no changelog available.

Could someone summarize what's the state of OpenStack4j and how it will be maintained in the future, especially considering CVE patching, etc?

Thanks

**Comment by olivergondza** [comment]
Yeah, the latest release details were drafted, but not published. Good point!

The maintenance status is what it is. While we are lucky in getting several contributors filing issues and PR, the cycles to validate and integrate them are scarce.
