### ISSUE TITLE
Not possible to detach a volume from a server

### ISSUE THREAD

**Issue by simosda** [openstack4j/openstack4j#22]
Hi,

I am trying to use Block Storage API V3 in order to detach a volume from a server.
The API call for that is /v3/{project_id}/volumes/{volume_id}/action with body containing attachment_id (it also works with server_id). I am not able to perform this call through the openstack4j client because I cannot find a way to get the attachmentId. There is a property "attachment_id" in CinderVolumeAttachment class but there is no getter for it. How can I get the attachmentId? Client version: 3.4.

**Comment by manuelmazzuola** [comment]
There is the `attachments` property inside the volume https://github.com/openstack4j/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java#L61

**Comment by manuelmazzuola** [comment]
https://github.com/openstack4j/openstack4j/blob/master/core-test/src/main/java/org/openstack4j/api/storage/VolumeTests.java#L87

**Comment by simosda** [comment]
The id getter in CinderVolumeAttachment is for the field id - this is not the attachment id, this is the id of the volume (checked with a example request) and cannot be used for detachment. Its value is of course different from the attachment_id property.

**Comment by simosda** [comment]
Below is the volume attachment part of the response from openstack and it is shown clearly that id = volume_id is actually the volume id, not attachment id. 

`[
  {
    'server_id': '6c8cf6e0-4c8f-442f-9196-9679737feec6',
    'attachment_id': '3dafcac4-1cb9-4b60-a227-d729baa10cf6',
    'attached_at': '2019-09-30T19:30:34.000000',
    'host_name': null,
    'volume_id': '5d95d5ee-4bdd-4452-b9d7-d44ca10d3d53',
    'device': '/dev/vda',
    'id': '5d95d5ee-4bdd-4452-b9d7-d44ca10d3d53'
  }
]`
