### ISSUE TITLE
when release the newest version sdk

### ISSUE THREAD

**Issue by wunaoaoshen** [openstack4j/openstack4j#232]
# Issue description

... i need some new feature which not exist in the version 3.11

## Submitter checklist

Make sure that following is specified to make the issue easier to process:

- [x] The issue description links to OpenStack API documentation of that particular endpoint/request (https://docs.openstack.org/api-ref/compute/#create-server).
- [x] OpenStack service name is used as an issue name prefix (ex.: "Neutron: Add floatingIp port forwardings service").
Compute: support block_device_mapping_v2 of create server
- [x] If applicable, add GitHub link to classes that needs extending.
https://github.com/openstack4j/openstack4j/pull/228

**Comment by olivergondza** [comment]
3.12 is out https://github.com/openstack4j/openstack4j/releases/tag/openstack4j-parent-3.12
