### ISSUE TITLE
The Openstack4j firewall only supports one firewall_policy_id?

### ISSUE THREAD

**Issue by liuhuagui** [openstack4j/openstack4j#56]
version: 3.6
![image](https://user-images.githubusercontent.com/21290865/81925378-03c4de00-9613-11ea-94aa-31aa10ca338b.png)
this is Openstack API doc. but implemention of the Openstack4j is as follow.
![image](https://user-images.githubusercontent.com/21290865/81925610-5605ff00-9613-11ea-82fc-1c51eb77369e.png)

**Comment by olivergondza** [comment]
Thanks for the report, please attach links instead of screenshots so this can be analyzed. Chances are the code needs to be adjusted to new version of the API.

**Comment by liuhuagui** [comment]
OpenStack API doc: https://docs.openstack.org/api-ref/network/v2/index.html?expanded=list-firewall-groups-detail#id283

**Comment by olivergondza** [comment]
@liuhuagui, the api resource `/v2.0/fwaas/firewall_groups` does not seem to be used by the library at all, so it is probably not implemented at all.

**Comment by liuhuagui** [comment]
We get `404` when accessed the api resource `/v2.0/fw/firewalls`，will the Openstack4j support those new api resources in the future?

**Comment by olivergondza** [comment]
That vastly depends on whether the support would be added by some of the library contributors.

**Comment by liuhuagui** [comment]
Thanks
