### ISSUE TITLE
EndpointURLResolver chooses wrong service endpoint from catalog

### ISSUE THREAD

**Issue by jkrue** [openstack4j/openstack4j#65]
After updating our  [application](https://github.com/BiBiServ/bibigrid) dependency from  openstack4j 3.0.4 to openstack4j > 3.0.4 the DefaultEndpointURLResolver chooses a wrong service endpoint for ServiceType COMPUTE on one of the de.NBI Openstack cloud sites (see https://github.com/BiBiServ/bibigrid/issues/235 for a description). In the current implementation the DefaultEndpointURLResolver selects a service endpoint for given service type when the type **or** the name matches. This behaviour is dangerous in the case of a partly misconfigured Openstack installation. In my opinion the type **and** the name should match the searched service type.

**Comment by olivergondza** [comment]
@jkrue, Thanks for the report.

Can you elaborate on what kind of OpenStack misconfiguration does this compensate? Have you found an authoritative documentation specifying the correct criteria for OS endpoint selection?

**Comment by jkrue** [comment]
Sure. The affected cloud site have two endpoints for the placement service with different names available. A request for a catalog returns :
```
...
"endpoints": [
          {
            "url": "https://cloud.computational.bio.uni-giessen.de/placement",
            "interface": "public",
            "region": "RegionOne",
            "region_id": "RegionOne",
            "id": "3a114b705e9a4a74a15e4a689e629c60"
          },
          ...        
        ],
        "type": "placement",
        "id": "ffc3a22349a2486f97a1736a8ce352e8",
        "name": "placement"
      },
      ...
           
"endpoints": [
          {
            "url": "https://cloud.computational.bio.uni-giessen.de/placement",
            "interface": "public",
            "region": "RegionOne",
            "region_id": "RegionOne",
            "id": "6ed596fc977f4816850396db7924ea3a"
          }
        ],
        "type": "placement",
        "id": "27368a214b964707b05ed27bd8fd883b",
        "name": "nova"
      }, 
     ...
```
In the meantime the cloud administrator of the affected cloud site removes the later one. He has no explanation why there are two endpoints with different names/ids for the same service are available.

Unfortunately, I did not found a documentation specifying the criteria for the endpoint selection. I think the most setups following the Openstack installation guides when initialising API endpoints. The typically and well known name(id)/type pairs like "nova/compute", "placement/placement", ... are adapted by all Openstack installations I know and also covered by Openstack4J `org.openstack4j.api.types.ServiceType`.

**Comment by olivergondza** [comment]
In such case, I suggest closing this as a deployment misconfiguration rather than a bug.
