### ISSUE TITLE
how to set httpClient keepAlive vaule

### ISSUE THREAD

**Issue by guoxingzhi** [openstack4j/openstack4j#70]
I want to ensure the availability of connections and clean up some timed out connections.
In this method org.openstack4j.connectors.httpclient.HttpClientFactory#buildClient，can set the KeepAliveStrategy of httpclient. 
When I use openstack4j, how should I set it？

**Comment by bboyHan** [comment]
You can use org.openstack4j.openstack.OSFactory#clientFromToken(Token token, Config config) to set org.openstack4j.core.transport.Config
