### ISSUE TITLE
I want to delete metadata of host-aggregates , but parameter lost after map serialization

### ISSUE THREAD

**Issue by zhaoyi4j** [openstack4j/openstack4j#71]
I want to delete metadata of host-aggregates , but parameter lost after map serialization。

This is my code.

>IClient client = clientService.getClient(controllerId);
>Map<String, String> metadata = new HashMap<>();
>metadata.put("pinned", null);
>client.compute().hostAggregates().setMetadata(id, metadata);

This request must run this code.
>String content = ObjectMapperSingleton.getContext(this.request.getEntity().getClass()).writer().writeValueAsString(this.request.getEntity());

There are the following parameters in class of org.openstack4j.core.transport.ObjectMapperSingleton:
>mapper.setSerializationInclusion(Include.NON_NULL);

HOW CAN I CHANGE THIS CONFIG TO
>mapper.setSerializationInclusion(Include.ALWAYS);

THANK YOU !!

**Comment by zhaoyi151205** [comment]
the map json of metadata is 
> {pinned: null}

**Comment by zhaoyi4j** [comment]
Yes，it  is desired is sending 'pinned: null', but it omits the field altogether!

**Comment by bboyHan** [comment]
is it ?  @zhaoyi4j 

link :  https://docs.openstack.org/api-ref/compute/?expanded=create-or-update-aggregate-metadata-detail#host-aggregates-os-aggregates
