### ISSUE TITLE
fault is left null in certain cases

### ISSUE THREAD

**Issue by bmaury-bouet** [openstack4j/openstack4j#79]
Dear all, 
I'm using 3.3 and I noticed now that we are also using regions (I don't know if it could be of some relevance) that some server seem to have their fault at null even when an error is present.
Using the official command line python client I can clearly see a fault object in the returned json file
I tried polling to see if it could be a timing issue, but the result is the same my server.fault is sitll null
Have you already seen this ?
Thanks

**Comment by bmaury-bouet** [comment]
So I found a change in behavior : 
if i do a
`List<? extends Server> servers = os.compute().servers().list(true);`
Then parse the list the servers that have faults are still having fault == null
but if I do : 
Server srv = os.compute().servers().get(serverId);
then fault is properly updated.

The strange thing is that the first case works on another region ... 
any idea ?

**Comment by bmaury-bouet** [comment]
Hi @olivergondza,
I enabled the wire, and when I compare the 2 calls ( the json from the full list and the json from the single server) there indeed a difference and the only field missing is "Fault" (at least in this case).

**Comment by bmaury-bouet** [comment]
@olivergondza  please note that on the other region (main region) I do see the "faut" in the json when calling list() (even with detailed==false)

**Comment by olivergondza** [comment]
@bmaury-bouet, that sure is interesting. Any difference in endpoint version in the other region? Different configs?

How does the python client present the fault in case it is not being served via REST?

**Comment by bmaury-bouet** [comment]
Hi @olivergondza unfortunately i'm don't have the full details on the different region I'll try to poke my colleagues in charge of the IT.
With python cli using "server list" or "server list --long" i never see the fault on both regions it doesn't show the fault I have to use server show {id} on both region to get the "fault" information

**Comment by bmaury-bouet** [comment]
@olivergondza  just got word from our IT departement 
So our "main" region is running on Newton version
and the new region runs on Stein.
So there might be a difference in behavior between the 2

**Comment by olivergondza** [comment]
Ok, so newton[1] have nova 14.1.0, stein[2] have nova 19.3.1. Which is quite a difference. I also understand it is the outdated version where this misbehaves. I have found no indication in the changelog of why would this change in between the versions.

I am closing this as not a problem of openstack4j - the server simply does not serve the needed data for whatever reason. Mind that Newton went EOL 2017-10-25.

[1] https://releases.openstack.org/newton/index.html
[2] https://releases.openstack.org/stein/index.html

**Comment by bmaury-bouet** [comment]
Sure no problem, we can easily bypass the issue.
I just wanted to make sure if could come from a bug on your end.
Thanks for the support @olivergondza !
