### ISSUE TITLE
I hope to get created_time and updated_time field but can not

### ISSUE THREAD

**Issue by bboyHan** [openstack4j/openstack4j#89]
When creating a network or subnet, I want to get the created time field and updated time field, but openstack4j does not provide it.

**Comment by olivergondza** [comment]
Thanks for the report. Please link the particular classes you are talking about here at github as well as relevant REST API docs (https://docs.openstack.org/api-ref/network/index.html) for facilitating review.

**Comment by bboyHan** [comment]
org.openstack4j.openstack.networking.domain.NeutronNetwork [NeutronSubnet | NeutronPort .etc] 

openstack - neutron plugin can provide time fields. so we can add the time fields to these class to get.

api link: https://docs.openstack.org/api-ref/network/v2/index.html#networks 

response body: (contains time fields - created_at | updated_at
{
"networks": [
        {
            "admin_state_up": true,
            "availability_zone_hints": [],
            "availability_zones": [
                "nova"
            ],
            "created_at": "2016-03-08T20:19:41",
            "dns_domain": "my-domain.org.",
            "id": "d32019d3-bc6e-4319-9c1d-6722fc136a22",
            "ipv4_address_scope": null,
            "ipv6_address_scope": null,
            "l2_adjacency": false,
            "mtu": 1500,
            "name": "net1",
            "port_security_enabled": true,
            "project_id": "4fd44f30292945e481c7b8a0c8908869",
            "qos_policy_id": "6a8454ade84346f59e8d40665f878b2e",
            "revision_number": 1,
            "router:external": false,
            "shared": false,
            "status": "ACTIVE",
            "subnets": [
                "54d6f61d-db07-451c-9ab3-b9609b6b6f0b"
            ],
            "tenant_id": "4fd44f30292945e481c7b8a0c8908869",
            "updated_at": "2016-03-08T20:19:41",
            "vlan_transparent": true,
            "description": "",
            "is_default": false
        }
}
