### ISSUE TITLE
Setting Volume name and description fails with Cinder "Rocky"

### ISSUE THREAD

**Issue by pjdarton** [openstack4j/openstack4j#9]
[BlockVolumeService.update(String volumeId, String name, String description)](https://github.com/ContainX/openstack4j/blob/3.2.0/core/src/main/java/org/openstack4j/openstack/storage/block/internal/BlockVolumeServiceImpl.java#L138) is used to set the name and description on a (Cinder) Volume.
This results in a JSON request being HTTP PUT to OpenStack containing the new name & description ... but it also includes `os-vol-mig-status-attr:migstat` = `none` with the rest of the JSON request, and the "Rocky" version of Cinder rejects that request:
```
ActionResponse{success=false, fault=Invalid input for field/attribute volume. Value: {u'description': u'...', u'display_name': u'...', u'name': u'...', u'os-vol-mig-status-attr:migstat': u'none', u'display_description': u'...'}. Additional properties are not allowed (u'os-vol-mig-status-attr:migstat' was unexpected), code=400}
```

i.e. the `update` method sets the `name` & `display_name` attributes to the `String name` it was given, and both the `description` & `display_description` attributes to the `String description` it was given, but it also tries to set attribute `os-vol-mig-status-attr:migstat` to `none`, which fails.

From what I've seen thus far, the underlying cause appears to be that [CinderVolume.getMigrateStatus()](https://github.com/openstack4j/openstack4j/blob/openstack4j-parent-3.3/core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolume.java#L182) does not return null if it has not been set; this then causes the JSON code to mistakenly believe it should be included in the outgoing request ... which causes Cinder to reject the (invalid) request.
According to the [javadocs](https://github.com/openstack4j/openstack4j/blob/openstack4j-parent-3.3/core/src/main/java/org/openstack4j/model/storage/block/Volume.java#L164), this field's default value should be null, but the existing implementation returns a default value of `MigrationStatus.NONE` instead of null.

i.e. it's not working as documented & it isn't working; this is probably cause & effect.

Note: The "Pike" version of Cinder doesn't seem to care about this and does not reject the request, allowing this issue to remain undetected for so long; the "Rocky" version does care and does reject it; I don't know about the "Queen" version.
Note also: The openstack4j has had numerous similar bugs in the past.  e.g. ContainX/openstack4j [#932](https://github.com/ContainX/openstack4j/pull/932), [#869](https://github.com/ContainX/openstack4j/issues/869), [#823](https://github.com/ContainX/openstack4j/issues/823), [#820](https://github.com/ContainX/openstack4j/pull/820), [#682](https://github.com/ContainX/openstack4j/issues/682), [#606](https://github.com/ContainX/openstack4j/issues/606), [#573](https://github.com/ContainX/openstack4j/issues/573), [#470](https://github.com/ContainX/openstack4j/issues/470).

**Comment by pjdarton** [comment]
After much detective work, my colleague found out...
> what has changed and caused the  "Additional properties are not allowed" error which is returned from Openstack.  In Rocky they now correctly validate the API input against allowed schema and reject anything that is not allowed by the API spec.  So previously it was allowing any additional rubbish on the API call.
```
    @validation.schema(volumes.update, mv.V2_BASE_VERSION,
                       mv.get_prior_version(mv.SUPPORT_VOLUME_SCHEMA_CHANGES))
    @validation.schema(volumes.update_volume_v353,
                       mv.SUPPORT_VOLUME_SCHEMA_CHANGES) 
```

i.e. that's why the presence of this "additional rubbish" wasn't picked up before :grin:

**Comment by olivergondza** [comment]
Nice find, no question the rubbish should have never been sent in the first place.
