### ISSUE TITLE
How to associate user with a machine

### ISSUE THREAD

**Issue by AlliParker-dev** [openstack4j/openstack4j#95]
Hi,

I'm studying openstack and programming, and I'm trying to create a machine and add the user and password already created to that machine, could someone help me?

My Code

 ```
final ServerCreate server = Builders.server()
        .name('test-machine')
        .flavor('1234567')
        .networks(Collections.singletonList("aev124b-1234-234-a8cc-2187654"))
        .addSecurityGroup('my_security_group'))
        .image('my_image_id')
        .build();

        // Boot the Server
        final Server server = os.compute().servers().boot(server);
        return "server created =)";
```

Create user

 ```
User user = os.identity().users().create(Builders.user()
                .domainId(domain.getId())
                .name("user")
                .password("1234")
                .email("test@gmail.com)
                .enabled(true)
                .defaultProjectId(project.getId())
                .build());
```

How do I add this user to my created machine?

**Comment by olivergondza** [comment]
@AlliParker-dev, please be more specific on what you are trying to achieve. Are you, by any change, trying to create a user account in the OS running in the server?

**Comment by AlliParker-dev** [comment]
@olivergondza, Yes. How do I create a user for this server that is running? 
It's possible? Is there a parameter to create this user when creating the machine?

**Comment by olivergondza** [comment]
That is not something OpenStack (or even openstack4j do). OpenStack delegates to [User Data](https://docs.openstack.org/nova/rocky/user/user-data.html) that you can use to tweak the VM configuration. Consult relevant documentation for the Operating System or images on how they handle User Data. Chances are they support cloud-init/cloud-config that have the ability to control user accounts.
