### ISSUE TITLE
pull request to allows users to set tags on their security group resources

### ISSUE THREAD

**Issue by bboyHan** [openstack4j/openstack4j#97]
rest api link : https://docs.openstack.org/api-ref/network/v2/?expanded=obtain-tag-list-detail,add-a-tag-detail,remove-all-tags-detail,confirm-a-tag-detail,remove-a-tag-detail,replace-all-tags-detail#subnets

I improved the api to facilitate the setting tags of the security group resources with users.

**Comment by olivergondza** [comment]
I am not familiar with the tagging approach, but from the docs it looks like it supports other kinds of resources than security groups *in a uniform manner*. It would be great to take advantage of that and implement general purpose tagging mechanism for all supported neutron entities, not just security groups.

**Comment by bboyHan** [comment]
I have considered general implementation, but I have not operated on resources other than server and security group in actual business, so I refer to other implementation methods about that org.openstack4j.openstack.compute.internal.ServerTagServiceImpl

**Comment by bboyHan** [comment]
A problem suddenly occurred to me that the endpoint called by nova, neutron and etc. will be different. 

Just like to set tags for servers (nova) :   nova.hostname:{port} /v2/servers/{server_id}/tags  
link : https://docs.openstack.org/api-ref/compute/?expanded=list-tags-detail#delete-server

set tags for security group (neutron) :  neutron.hostname:{port} /v2/security_groups/{security_group_id}/tags

If we want to set tags for another plugin, the endpoint may be {another plugin}.hostname:{port} /v1/{resource}/{resource_id}/...

This may be the reason why they haven't written a general implementation before.

**Comment by olivergondza** [comment]
@bboyHan, interesting observation. So neutron permit several resource types to be tagged[1], but compute permit tagging of servers only[2]. My suggestion was to treat networks, ports, subnets, subnet pools, floating IPs, routers, security groups, security group rules, QoS policies and trunks uniformly - that was before you have made me aware that servers can be tagged to.

While the APIs[1,2] seem somewhat similar, they appear to be implemented independently by OpenStack and it would be wise to have a separate implementation for them.

Let's keep server tagging to `ServerTagService`, but I suggest making this general neutron implementation for tagging all documented resource types supported by neutron.

WDYT, @bboyHan?

[1] https://docs.openstack.org/api-ref/network/v2/index.html#standard-attributes-tag-extension
[2] https://docs.openstack.org/api-ref/compute/#server-tags-servers-tags

**Comment by bboyHan** [comment]
Thanks for your nice suggestion. I made it to be a general neutron implementation for tagging. 

#98

**Comment by bboyHan** [comment]
merged
